name: SmartContracts
on: [ push, pull_request ]

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  SEPOLIA_API_URL: ${{ secrets.SEPOLIA_API_URL }}
  
jobs:
  test:
    name: Test Smart Contracts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd smartcontracts
          npm install
      - name: Run tests
        run: |
          cd smartcontracts
          npx hardhat test
